// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: common.proto
#ifndef GRPC_common_2eproto__INCLUDED
#define GRPC_common_2eproto__INCLUDED

#include "common.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace org {
namespace beachc {
namespace deep_thought {
namespace common {

}  // namespace common
}  // namespace deep_thought
}  // namespace beachc
}  // namespace org


#endif  // GRPC_common_2eproto__INCLUDED
