// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: deep_thought.proto
#ifndef GRPC_deep_5fthought_2eproto__INCLUDED
#define GRPC_deep_5fthought_2eproto__INCLUDED

#include "deep_thought.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace org {
namespace beachc {
namespace deep_thought {

class Emulator final {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::org::beachc::deep_thought::MachineState, ::org::beachc::deep_thought::VideoFrame>> initialize(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::org::beachc::deep_thought::MachineState, ::org::beachc::deep_thought::VideoFrame>>(initializeRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::org::beachc::deep_thought::MachineState, ::org::beachc::deep_thought::VideoFrame>> Asyncinitialize(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::org::beachc::deep_thought::MachineState, ::org::beachc::deep_thought::VideoFrame>>(AsyncinitializeRaw(context, cq, tag));
    }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::org::beachc::deep_thought::MachineState, ::org::beachc::deep_thought::VideoFrame>* initializeRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::org::beachc::deep_thought::MachineState, ::org::beachc::deep_thought::VideoFrame>* AsyncinitializeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::org::beachc::deep_thought::MachineState, ::org::beachc::deep_thought::VideoFrame>> initialize(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::org::beachc::deep_thought::MachineState, ::org::beachc::deep_thought::VideoFrame>>(initializeRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::org::beachc::deep_thought::MachineState, ::org::beachc::deep_thought::VideoFrame>> Asyncinitialize(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::org::beachc::deep_thought::MachineState, ::org::beachc::deep_thought::VideoFrame>>(AsyncinitializeRaw(context, cq, tag));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReaderWriter< ::org::beachc::deep_thought::MachineState, ::org::beachc::deep_thought::VideoFrame>* initializeRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::org::beachc::deep_thought::MachineState, ::org::beachc::deep_thought::VideoFrame>* AsyncinitializeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    const ::grpc::RpcMethod rpcmethod_initialize_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status initialize(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::org::beachc::deep_thought::VideoFrame, ::org::beachc::deep_thought::MachineState>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_initialize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_initialize() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_initialize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status initialize(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::org::beachc::deep_thought::VideoFrame, ::org::beachc::deep_thought::MachineState>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestinitialize(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::org::beachc::deep_thought::VideoFrame, ::org::beachc::deep_thought::MachineState>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_initialize<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_initialize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_initialize() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_initialize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status initialize(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::org::beachc::deep_thought::VideoFrame, ::org::beachc::deep_thought::MachineState>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace deep_thought
}  // namespace beachc
}  // namespace org


#endif  // GRPC_deep_5fthought_2eproto__INCLUDED
