// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nes.proto

#include "nes.pb.h"
#include "nes.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace org {
namespace beachc {
namespace deep_thought {
namespace nes {

}  // namespace org
}  // namespace beachc
}  // namespace deep_thought
}  // namespace nes

